name: Arzon
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  provider: ^6.1.1

  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2

  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  flutter_dotenv: ^5.1.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/banners/
    - assets/items/
    - assets/small/
    - assets/big/
    - assets/icons/

  # example:
  fonts:
    - family: Yackien
      fonts:
        - asset: assets/fonts/Yackien.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
